// TEST_F(BufferFx, multi_test) {
//    auto test_strings = std::vector<std::string>{"itannalainia",
//                                                 "iaumchiaheanne",
//                                                 "iauchiaheanne",
//                                                 "iiauchiaheanneou",
//                                                 "iniauchiaheanneou",
//                                                 "naapinnhiaboa",
//                                                 "naapinnhiaaboeu",
//                                                 "naapinnhiaabeu",
//                                                 "khachiahauoe",
//                                                 "simsianne",
//                                                 "simsekiaho",
//                                                 "tiasitihia",
//                                                 "inaesitihia",
//                                                 "inahesitihia",
//                                                 "oathng",
//                                                 "chiahoathng",
//                                                 "oatihaite",
//                                                 "ouatihaite",
//                                                 "chiteaichiahoa",
//                                                 "chiteaichiahoua",
//                                                 "oanaesitihia",
//                                                 "oanahesitihia",
//                                                 "ahanahesitihia",
//                                                 "chitchiahaha",
//                                                 "chitboehia",
//                                                 "chitbehia",
//                                                 "hianaheboboe",
//                                                 "hianahebobe",
//                                                 "kannaaitihoa",
//                                                 "sinithiann",
//                                                 "sisinithiann",
//                                                 "chhiti",
//                                                 "chhitia",
//                                                 "poetemthangchhikimhi",
//                                                 "ohhouho",
//                                                 "ohhooho",
//                                                 "aiohhouhoou",
//                                                 "aiohhoohooo",
//                                                 "aiohhoohoou",
//                                                 "aiohhouhooo",
//                                                 "ohhouhoaboe",
//                                                 "ohhoohoaboe",
//                                                 "ohhoohoabe"};
//
//    for (auto &s : test_strings) {
//        reset();
//        insert(s);
//    }
//}
